### PR TITLE
Update for basic compatibility with sd-webui-v1.5

### PR DESCRIPTION
**Pull request by zixaphir**
Version 1.5.0 introduced a few changes to Stable Diffusion WebUI that broke compatibility with the Stable-Diffusion-Webui-Civitai-Helper script. I reworked parts of the script to address these changes and restore functionality.

### CODE REVIEW

**Comment by kuso-ge** [comment]
Thanks! Your fix works

**Comment by N1ghtB3ast** [comment]
Thank you, greatly appreciated

**Comment by teerasak2545** [comment]
What do I have to do with this I don't know how to fix it.

**Comment by wangnimaaa** [comment]
The plugin failed, and the button was not displayed again

**Comment by BaseMe2** [comment]
With WebUI 1.5.2 it throws a hint:
```
a1111-sd-webui-lycoris 
Starting from stable-diffusion-webui version 1.5.0
a1111-sd-webui-lycoris extension is no longer needed
All its features have been integrated into the native LoRA extension 
LyCORIS models can now be used as if there are regular LoRA models
This extension has been automatically deactivated
Please remove this extension
```

Disabling the LyCORIS extension will throw errors. Keeping it enabled seams to work for now. 
Lightbulb for easy insertion of prompts no longer exists, even if clicked on the tool icon.


```
Civitai Helper: Get Custom Model Folder
*** Error loading script: civitai_helper.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 36, in <module>
        model.get_custom_model_folder()
      File "D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model.py", line 46, in get_custom_model_folder
        if shared.cmd_opts.lyco_dir and os.path.isdir(shared.cmd_opts.lyco_dir):
    AttributeError: 'Namespace' object has no attribute 'lyco_dir'
```

Going forward the dependency on the LyCORIS extension needs to get moved to main. 
a1111 v1.6 RC is also already available.

**Comment by zixaphir** [comment]
Currently I'm doing additional development on my own fork until this gets merged: https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/
I don't really want to be a maintainer for an extension but since I'm doing changes for myself anyways, I might as well share. I'll look at issues and make best-effort attempts to fix them, but I'm honestly just a hobbyist with minimal development experience.

**Comment by zixaphir** [comment]
> With WebUI 1.5.2 it throws a hint:
> 
> ```
> a1111-sd-webui-lycoris 
> Starting from stable-diffusion-webui version 1.5.0
> a1111-sd-webui-lycoris extension is no longer needed
> All its features have been integrated into the native LoRA extension 
> LyCORIS models can now be used as if there are regular LoRA models
> This extension has been automatically deactivated
> Please remove this extension
> ```
> 
> Disabling the LyCORIS extension will throw errors. Keeping it enabled seams to work for now. Lightbulb for easy insertion of prompts no longer exists, even if clicked on the tool icon.
> 
> ```
> Civitai Helper: Get Custom Model Folder
> *** Error loading script: civitai_helper.py
>     Traceback (most recent call last):
>       File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 36, in <module>
>         model.get_custom_model_folder()
>       File "D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model.py", line 46, in get_custom_model_folder
>         if shared.cmd_opts.lyco_dir and os.path.isdir(shared.cmd_opts.lyco_dir):
>     AttributeError: 'Namespace' object has no attribute 'lyco_dir'
> ```
> 
> Going forward the dependency on the LyCORIS extension needs to get moved to main. a1111 v1.6 RC is also already available.

 

If you're using my code, this error should not be possible. The block in question has been changed to account for the addon either being there or not being there since commit, https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/6f95dd201acd76b98da9d096691ef5b41fb438bf, with additional changes in https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/ccb16925b320e695387666ffbbe058fcb15fbcf0

turning this:
```python
        folders["lycoris"] = shared.cmd_opts.lyco_dir
```
into this:
```python
    try:
        # pre-1.5.0
        if shared.cmd_opts.lyco_dir and os.path.isdir(shared.cmd_opts.lyco_dir):
            folders["lycoris"] = shared.cmd_opts.lyco_dir

    except:
        try:
            # sd-webui v1.5.1 added a backcompat option for lyco.
            if shared.cmd_opts.lyco_dir_backcompat and os.path.isdir(shared.cmd_opts.lyco_dir_backcompat):
                folders["lycoris"] = shared.cmd_opts.lyco_dir_backcompat
        except:
            # XXX v1.5.0 has no options for the Lyco dir: it is hardcoded as 'os.path.join(paths.models_path, "LyCORIS")'
            pass
```

which should completely avoid that error.

**Comment by BaseMe2** [comment]
Yes your code works. Thanks a lot zixaphir. 
I hope you'll find time making it work with the upcoming 1.6 as well. 
You're my hero. This extension is a must have in my eyes.

**Comment by zixaphir** [comment]
I'm closing this since merging now makes little sense.
